---

- name: Configure EDA Project HAPROXY
  hosts: localhost
  gather_facts: false

  vars:
    eda_host: https://eda.localnet.local
    eda_username: admin
    eda_password: r3dh4t1!
    validate_certs: false
    description_project: "CaC install haproxy project"
    config_eda_estado: present

    project_git:
      name: haproxy-http
      url: https://github.com/laurobmb/haproxy-http.git
      token: 'integration_token'
      branch: main

    project_rulebook_activation:
      - name: CheckWebServer
        rulebook: rulebook-check-webserver.yml
        decision_environment: Default Decision Environment
        enabled: true

  tasks:

    - name: Create Project
      ansible.builtin.import_tasks: eventdriven/projeto_haproxy_project.yml

    - name: Create Rulebook
      ansible.builtin.import_tasks: eventdriven/projeto_haproxy_rulebook_activation.yml
