---
- name: Validate SSL certificate and private key
  hosts: localhost
  gather_facts: false
  vars:
    certificate_path: /path/to/certificate.crt
    private_key_path: /path/to/private.key

  tasks:
    - name: Get modulus from the certificate
      ansible.builtin.command:
        cmd: "openssl x509 -noout -modulus -in {{ certificate_path }} | openssl md5"
      register: cert_modulus

    - name: Get modulus from the private key
      ansible.builtin.command:
        cmd: "openssl rsa -noout -modulus -in {{ private_key_path }} | openssl md5"
      register: key_modulus

    - name: Compare the certificate and key modulus
      ansible.builtin.debug:
        msg: "Certificate and key match!"
      when: cert_modulus.stdout == key_modulus.stdout

    - name: Fail if certificate and key do not match
      ansible.builtin.fail:
        msg: "Certificate and private key do not match!"
      when: cert_modulus.stdout != key_modulus.stdout
