---
- name: Register maquinas
  hosts: all
  gather_facts: false
  tasks:
    - name: Coletando fatos
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - "!min"
          - network
          - "!facter"
          - "!processor"

    - name: Check web site from web server
      ansible.builtin.uri:
        url: http://{{ ansible_default_ipv4.address }}/
        return_content: true
      register: webpage

    - name: Verificar se o conteúdo está presente na resposta
      ansible.builtin.assert:
        that:
          - "'Informações do Servidor' in webpage.content"
        fail_msg: "O conteúdo não foi encontrado na página web"
