---
- name: Register maquinas
  hosts: haproxy
  gather_facts: false
  pre_tasks:
    - name: Install common packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - net-tools
        - bind-utils
        - firewalld
    - name: Coletando fatos para gerar relatorio
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - "!min"
          - network
          - "!facter"
          - processor
  roles:
    - role: haproxy
      when: "ansible_os_family == 'RedHat'"
      tags: install_haproxy
