---
- name: Register maquinas
  hosts: web_servers
  gather_facts: false
  pre_tasks:
    - name: Install common packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - net-tools
        - bind-utils
        - firewalld
    - name: Coletando fatos
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - "!min"
          - network
          - "!facter"
          - processor
  roles:
    - role: httpd
      tags: install_httpd
