- name: Get modulus from the certificate
  ansible.builtin.shell: "openssl x509 -noout -modulus -in {{ dest_diretorio }}/{{ item }}.pem | openssl md5"
  register: cert_modulus
  loop: "{{ domains }}"

- name: Get modulus from the private key
  ansible.builtin.shell: "openssl rsa -noout -modulus -in {{ dest_diretorio }}/{{ item }}.key | openssl md5"
  register: key_modulus
  loop: "{{ domains }}"

- name: Debug
  ansible.builtin.debug:
    var: cert_modulus

- name: Compare the certificate and key modulus
  ansible.builtin.assert:
    that:
      - item.0.stdout == item.1.stdout
    success_msg: "Certificate and key match!"
    fail_msg: "Certificate and key is not match!"
  with_together:
    - "{{ cert_modulus.results }}"
    - "{{ key_modulus.results }}"
