---

- name: Create Credentials AcessoHosts
  ansible.controller.credential:
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    controller_host: "{{ controller_host }}"
    validate_certs: "{{ validate_certs }}"
    name: AcessoHosts
    credential_type: Machine
    organization: "{{ organization }}"
    description: "{{ description_project }}"
    state: "{{ config_aap_estado }}"
    inputs:
      username: root
      password: redhat

- name: Create Credentials AcessoHUB
  ansible.controller.credential:
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    controller_host: "{{ controller_host }}"
    validate_certs: "{{ validate_certs }}"
    name: AcessoHUB
    credential_type: Container Registry
    organization: "{{ organization }}"
    description: "{{ description_project }}"
    state: "{{ config_aap_estado }}"
    inputs:
      username: lagomes
      password: vs9mrD55NP
      verify_ssl: false

- name: Create Credentials AcessoGitlab
  ansible.controller.credential:
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    controller_host: "{{ controller_host }}"
    validate_certs: "{{ validate_certs }}"
    name: AcessoGitlab
    credential_type: Source Control
    organization: "{{ organization }}"
    description: "{{ description_project }}"
    state: "{{ config_aap_estado }}"
    inputs:
      username: "laurobmb@gmail.com"
      ssh_key_data: "{{ aws_ssh_key }}"