---

- name: Create execution environments
  ansible.controller.execution_environment:
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    controller_host: "{{ controller_host }}"
    validate_certs: "{{ validate_certs }}"
    organization: "{{ organization }}"
    description: "{{ description_project }}"
    state: "{{ config_aap_estado }}"

    name: "{{ item.name }}"
    image: "{{ item.image }}"
    pull: "{{ item.pull }}"
    credential: "{{ item.credential | default(omit) }}"
  loop: "{{ project_execution_environments }}"


