---
controller_hosts:
  - name: "haproxy.localnet.local"
    inventory: haproxy_project_inventory
    enabled: true
    description: "DevOps and Automation Team"
    variables:
      example_var: 123
      ansible_host: 192.168.184.14

  - name: "web1.localnet.local"
    inventory: haproxy_project_inventory
    enabled: true
    description: "DevOps and Automation Team"
    variables:
      example_var: 123
      ansible_host: 192.168.184.12

  - name: "web2.localnet.local"
    inventory: haproxy_project_inventory
    enabled: true
    description: "DevOps and Automation Team"
    variables:
      example_var: 123
      ansible_host: 192.168.184.13

