# curl -H 'Content-Type: application/json' -d "{\"message\": \"install webservers is cool\"}" eda.localnet.local:5003

---
- name: Install WebServers
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5005
  rules:
    - name: Condicao DEBUG
      condition: event.payload is defined
      action:
        debug:
          var: event.payload
