# curl -H 'Content-Type: application/json' -d "{\"message\": \"install webservers is cool\"}" eda.localnet.local:5003

---
- name: Install WebServers
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003
  rules:
    - name: here is a generic rule
      condition: event.payload.message is defined
      action:
        debug:
          var: event

    - name: Install WebServers
      condition: event.payload.message == "install webservers is cool"
      action:
        run_job_template:
          name: main-http
          organization: Devops
