# curl -H 'Content-Type: application/json' -d "{\"message\": \"install haproxy is cool\"}" eda.localnet.local:5004

---
- name: Install HAPROXY
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5004
  rules:
    - name: Install HAPROXY
      condition: event.payload.message == "install haproxy is cool"
      action:
        run_job_template:
          name: main-haproxy
          organization: Devops
