---
- name: Install HAPROXY
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5004
  rules:
    - name: Say Hello 2
      condition: event.payload.message == "Ansible template is cool"
      action:
        run_job_template:
          name: main-haproxy
          organization: Devops
