---
- name: Ansible template is cool
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003
  rules:
    - name: Say Hello 2
      condition: event.payload.message == "Ansible template is cool"
      action:
        run_job_template:
          name: Automation - Check Webpage
          organization: "Default"
