---
# tasks file for httpd_example

- name: Coletando nome do servidor
  ansible.builtin.command:
    argv:
      - hostname
      - -s
  register: ansible_hostname
  changed_when: false

- name: DEBUG Mostrando caminhos
  ansible.builtin.set_fact:
    ansible_hostname: "{{ ansible_hostname.stdout }}"

- name: Install httpd
  ansible.builtin.yum:
    name: '{{ __apache_packages }}'
    state: present
  notify: restart httpd

- name: Install common packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - net-tools
    - bind-utils
    - firewalld

- name: Allow firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    zone: public
    immediate: yes
  loop:
  - https
  - http

- name: Copy index
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart httpd
