---
# tasks file for httpd_example

- name: Coletando nome do servidor
  ansible.builtin.command:
    argv:
      - hostname
      - -s
  register: ansible_hostname
  changed_when: false

- name: DEBUG Mostrando caminhos
  ansible.builtin.set_fact:
    ansible_hostname: "{{ ansible_hostname.stdout }}"

- name: Install httpd
  ansible.builtin.yum:
    name: '{{ __apache_packages }}'
    state: present
  notify: restart httpd

- name: Allow firewalld
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    zone: public
    immediate: true
  loop:
    - https
    - http

- name: Copy index
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: restart httpd
